import { type NextPage } from "next";
import Head from "next/head";

import Layout from "~/components/Layout";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Reaxion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/pngegg.png" />
      </Head>
      <main className="bg-veryLightGray">
        <Layout />
      </main>
    </>
  );
};

export default Home;
